In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats as spt
import statsmodels.api as sm
from statsmodels.formula.api import ols
from scipy import stats as sps
import seaborn as sns
import statsmodels.stats.proportion as ssp
import geopandas as gpd

In [8]:
df = sns.load_dataset('tips')

In [10]:
df.sample(8)

total_bill   tip     sex smoker   day    time  size
97        12.03  1.50    Male    Yes   Fri  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2
46        22.23  5.00    Male     No   Sun  Dinner     2
144       16.43  2.30  Female     No  Thur   Lunch     2
65        20.08  3.15    Male     No   Sat  Dinner     3
58        11.24  1.76    Male    Yes   Sat  Dinner     2
117       10.65  1.50  Female     No  Thur   Lunch     2
54        25.56  4.34    Male     No   Sun  Dinner     4

In [61]:
var1='sex'
var2='time'
# crosstab creates a summary table that represents the frequencies (observed) values of each category.
# dfCrossTab = pd.crosstab(df['time'],df['smoker'])
dfCrossTab = pd.crosstab(df[var1],df[var2])

dfCrossTab

time    Lunch   Dinner
sex                   
Male        33     124
Female      35      52

In [62]:
# you can see the observed values as an array
observed_values = dfCrossTab.values
print(observed_values)

[[ 33 124]
 [ 35  52]]


### The SciPy way! for 2X2 contingency tables

In [36]:
# see how the fucntion works
sps.chi2_contingency?

Signature: sps.chi2_contingency(observed, correction=True, lambda_=None)
Docstring:
Chi-square test of independence of variables in a contingency table.

This function computes the chi-square statistic and p-value for the
hypothesis test of independence of the observed frequencies in the
contingency table [1]_ `observed`.  The expected frequencies are computed
based on the marginal sums under the assumption of independence; see
`scipy.stats.contingency.expected_freq`.  The number of degrees of
freedom is (expressed using numpy functions and attributes)::

    dof = observed.size - sum(observed.shape) + observed.ndim - 1


Parameters
----------
observed : array_like
    The contingency table. The table contains the observed frequencies
    (i.e. number of occurrences) in each category.  In the two-dimensional
    case, the table is often described as an "R x C table".
correction : bool, optional
    If True, *and* the degrees of freedom is 1, apply Yates' correction
    for continuity. 

what is correction?
The Yates correction is made to account for the fact that both Pearson’s chi-square test and McNemar’s chi-square test are biased upwards for a 2 x 2 contingency table. An upwards bias tends to make results larger than they should be. If you are creating a 2 x 2 contingency table that uses either of these two tests, the Yates correction is usually recommended, especially if the expected cell frequencies are below 10 (some authors put that figure at 5).

In [63]:
# Returns
# -------
# [0]chi2 : float
#     The test statistic.
# [1]p : float
#     The p-value of the test
# [2]dof : int
#     Degrees of freedom ((#rows -1)*(#cols-1))
# [3]expected : ndarray, same shape as `observed`
#     The expected frequencies, based on the marginal sums of the table.

results = sps.chi2_contingency(dfCrossTab)
print (results)

(9.343808982970623, 0.002237400118075248, 1, array([[ 43.75409836, 113.24590164],
       [ 24.24590164,  62.75409836]]))


In [64]:
pValue=results[1]
print ('P-Value is: ',pValue)

P-Value is:  0.002237400118075248


In [43]:
# degree of freedom
print ('degree of freedom is: ', results[2])

degree of freedom is:  1


In [25]:
# get the expected values from the results list
# print(results[3])
print(results[3].astype('int'))

[[59 97]
 [33 53]]


In [40]:
# you can see the observed values as an array
observed_values = dfCrossTab.values
print(observed_values)

[[60 97]
 [33 54]]


For a Chi-square test, a p-value that is less than or equal to your significance level indicates there is sufficient evidence to conclude that the observed distribution is not the same as the expected distribution. You can conclude that a relationship exists between the categorical variables.

For example, if the p-value is 0.01 it means that you are taking 1% risk to say that difference between observed and expected values is a real difference and represents the population. 

In [70]:
# this is basically the risk level that you can set for yourself 0.01 is 1%
significanceLevel = 0.01

In [71]:
if pValue<=significanceLevel:
    print('Reject the null hypothesis; there is a relationship between two categorical variables')
else:
    print('Accept the null hypothesis; there is no relationship betwee two categorical variables')

Reject the null hypothesis; there is a relationship between two categorical variables
